Repository jsgith/buenavista, pull requests merged in 2025-01, with the labels that each got.

#9 Change sobrenosotros section, delete test posts and first post
  README.md
  _posts/2025-01-03-teste.md
  _posts/2025-01-08-teste-marta.md
  _posts/2025-01-12-8443-km-benedita-buena-vista.md
Labels: enhancement, post

#10 Add one more \n to the post to separate excert from full text
  _posts/2025-01-12-8443-km-benedita-buena-vista.md
Labels: bug

#11 Bold the items in the list of fun facts
  README.md
Labels: minor improvement
